name: latest-build-bluespice-web

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - bluespice-web/**

jobs:
  build-bluespice-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./bluespice-web
        file: ./bluespice-web/Dockerfile
        push: true
        tags: | 
          ${{ secrets.DOCKER_HUB_USERNAME }}/bluespice-web:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/bluespice-web:${{ github.run_id }}